//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify username!.
        /// </summary>
        public static string ErrorMessage3000 {
            get {
                return ResourceManager.GetString("ErrorMessage3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify password!.
        /// </summary>
        public static string ErrorMessage3010 {
            get {
                return ResourceManager.GetString("ErrorMessage3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or password is not correct!.
        /// </summary>
        public static string ErrorMessage3020_3030 {
            get {
                return ResourceManager.GetString("ErrorMessage3020_3030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not verified!.
        /// </summary>
        public static string ErrorMessage3040 {
            get {
                return ResourceManager.GetString("ErrorMessage3040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active!.
        /// </summary>
        public static string ErrorMessage3050 {
            get {
                return ResourceManager.GetString("ErrorMessage3050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expire time did not specify for this user!.
        /// </summary>
        public static string ErrorMessage3060 {
            get {
                return ResourceManager.GetString("ErrorMessage3060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account expired!.
        /// </summary>
        public static string ErrorMessage3070 {
            get {
                return ResourceManager.GetString("ErrorMessage3070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify user IP!.
        /// </summary>
        public static string ErrorMessage3080 {
            get {
                return ResourceManager.GetString("ErrorMessage3080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP did not defined!.
        /// </summary>
        public static string ErrorMessage3090 {
            get {
                return ResourceManager.GetString("ErrorMessage3090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP is not verified!.
        /// </summary>
        public static string ErrorMessage3100 {
            get {
                return ResourceManager.GetString("ErrorMessage3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP is not active!.
        /// </summary>
        public static string ErrorMessage3110 {
            get {
                return ResourceManager.GetString("ErrorMessage3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use one uppercase letter at least.
        /// </summary>
        public static string ErrorMessage3120 {
            get {
                return ResourceManager.GetString("ErrorMessage3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use one number at least.
        /// </summary>
        public static string ErrorMessage3130 {
            get {
                return ResourceManager.GetString("ErrorMessage3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is not match with password.
        /// </summary>
        public static string ErrorMessage3140 {
            get {
                return ResourceManager.GetString("ErrorMessage3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this page.
        /// </summary>
        public static string ErrorMessage406 {
            get {
                return ResourceManager.GetString("ErrorMessage406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a duplicate username.
        /// </summary>
        public static string IsDuplicateUsername {
            get {
                return ResourceManager.GetString("IsDuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max. length of {0} should be {1}!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes at least 8 character!.
        /// </summary>
        public static string MinCharacter {
            get {
                return ResourceManager.GetString("MinCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The min. length of {0} should be {1}!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify a valid cell phone number!.
        /// </summary>
        public static string RegularExpressionForCellPhoneNumber {
            get {
                return ResourceManager.GetString("RegularExpressionForCellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer or double numbers!.
        /// </summary>
        public static string RegularExpressionForDouble {
            get {
                return ResourceManager.GetString("RegularExpressionForDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address!.
        /// </summary>
        public static string RegularExpressionForEmail {
            get {
                return ResourceManager.GetString("RegularExpressionForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 1 - 100 characters..
        /// </summary>
        public static string RegularExpressionForFileName {
            get {
                return ResourceManager.GetString("RegularExpressionForFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer numbers!.
        /// </summary>
        public static string RegularExpressionForInteger {
            get {
                return ResourceManager.GetString("RegularExpressionForInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid!.
        /// </summary>
        public static string RegularExpressionForMoney {
            get {
                return ResourceManager.GetString("RegularExpressionForMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains 10 digits..
        /// </summary>
        public static string RegularExpressionForNationalCode {
            get {
                return ResourceManager.GetString("RegularExpressionForNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 8 - 40 characters..
        /// </summary>
        public static string RegularExpressionForPassword {
            get {
                return ResourceManager.GetString("RegularExpressionForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you should use numbers between 0.00 to 100.00!.
        /// </summary>
        public static string RegularExpressionForPercentage {
            get {
                return ResourceManager.GetString("RegularExpressionForPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid url address!.
        /// </summary>
        public static string RegularExpressionForUrl {
            get {
                return ResourceManager.GetString("RegularExpressionForUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 6 - 20 characters..
        /// </summary>
        public static string RegularExpressionForUsername {
            get {
                return ResourceManager.GetString("RegularExpressionForUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer numbers &gt;=0.
        /// </summary>
        public static string RegularExpressionForZeroOrUnsignedInteger {
            get {
                return ResourceManager.GetString("RegularExpressionForZeroOrUnsignedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {1} characters!.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error!.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
